apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hr
  template:
    metadata:
      labels:
        app: hr
    spec:
      containers:
        - name: hr-container
          image: hr-service
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
          env:
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:3000/validate"
            - name: DB_HOST
              value: "hr-db-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: HR_DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: HR_DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: HR_DB_PASSWORD
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: hr-service
spec:
  selector:
    app: hr
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP