apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-db
  template:
    metadata:
      labels:
        app: storage-db
    spec:
      containers:
        - name: storage-db-container
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: STORAGE_DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: STORAGE_DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: STORAGE_DB_NAME
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: storage-db-service
spec:
  selector:
    app: storage-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP