apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
        - name: storage-container
          image: storage-service
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          env:
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:3000/validate"
            - name: DB_HOST
              value: "storage-db-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: STORAGE_DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: STORAGE_DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: STORAGE_DB_PASSWORD
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: storage-service
spec:
  selector:
    app: storage
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP